spring:
  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:55641/railway
    username: postgres
    password: jKPPNEcAhKOzsUVKYzPSPKKLMiECriOt
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update